### ISSUE TITLE
Running git hooks does not work for fresh git repos

### ISSUE THREAD

**Issue by OmegaDroid** [wildfish/git-hooks#4]
Looks like we are getting the error because `refs/heads/master` doesn't already exist

```
Traceback (most recent call last):
  File ".git/hooks/pre-commit", line 7, in <module>
    sys.exit(runners.PreCommitHookRunner().run())
  File "/home/dan/.virtualenvs/git-hooks/lib/python3.4/site-packages/githooks/runners.py", line 63, in run
    args = list(self.get_process_args())
  File "/home/dan/.virtualenvs/git-hooks/lib/python3.4/site-packages/githooks/runners.py", line 85, in get_process_args
    args += tuple(repo.added_files() + repo.modified_files())
  File "/home/dan/.virtualenvs/git-hooks/lib/python3.4/site-packages/githooks/repo.py", line 56, in added_files
    return [os.path.join(repo_root_dir, d.a_path) for d in get().head.commit.diff() if d.new_file]
  File "/home/dan/.virtualenvs/git-hooks/lib/python3.4/site-packages/git/refs/symbolic.py", line 183, in _get_commit
    obj = self._get_object()
  File "/home/dan/.virtualenvs/git-hooks/lib/python3.4/site-packages/git/refs/symbolic.py", line 176, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/home/dan/.virtualenvs/git-hooks/lib/python3.4/site-packages/git/refs/symbolic.py", line 125, in dereference_recursive
    hexsha, ref_path = cls._get_ref_info(repo, ref_path)
  File "/home/dan/.virtualenvs/git-hooks/lib/python3.4/site-packages/git/refs/symbolic.py", line 157, in _get_ref_info
    raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at 'refs/heads/master' does not exist
```

**Comment by OmegaDroid** [comment]
I've added an error for now stating you need to do an initial commit before you can initialise git hooks
